---
- name: ensure zsh installed
  become: true
  community.general.pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    state: latest
    update_cache: true

- name: ensure zsh allowed as a shell
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /bin/zsh

- name: ensure zsh is "{{ ansible_user_id }}'s" default shell
  become: true
  ansible.builtin.shell: "chsh -s /bin/zsh {{ ansible_user_id }}"

- name: setup "{{ ansible_user_id }}'s" .zshrc
  ansible.builtin.template:
    src: templates/zshrc.j2
    dest: "/home/{{ ansible_user_id }}/.zshrc"

- name: setup "{{ ansible_user_id }}'s" .zshenv
  ansible.builtin.template:
    src: templates/zshenv.j2
    dest: "/home/{{ ansible_user_id }}/.zshenv"
