---
- name: install gnome packages
  become: true
  community.general.pacman:
    name:
      - baobab
      - cheese
      - eog
      - evince
      - file-roller
      - gdm
      - gnome-backgrounds
      - gnome-calculator
      - gnome-characters
      - gnome-clocks
      - gnome-color-manager
      - gnome-control-center
      - gnome-disk-utility
      - gnome-documents
      - gnome-font-viewer
      - gnome-keyring
      - gnome-logs
      - gnome-menus
      - gnome-photos
      - gnome-remote-desktop
      - gnome-screenshot
      - gnome-session
      - gnome-settings-daemon
      - gnome-shell
      - gnome-shell-extensions
      - gnome-system-monitor
      - gnome-themes-extra
      - gnome-user-docs
      - gnome-user-share
      - gnome-video-effects
      - grilo-plugins
      - gvfs
      - gvfs-afc
      - gvfs-goa
      - gvfs-google
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - mutter
      - nautilus
      - rygel
      - simple-scan
      - sushi
      - tracker
      - tracker-miners
      - tracker3
      - tracker3-miners
      - vino
      - xdg-user-dirs-gtk
      - yelp
    state: latest
    update_cache: true

- name: enable pulseaudio
  systemd:
    enabled: true
    scope: user
    state: started
    name: pulseaudio

- name: enable gdm service
  become: true
  systemd:
   enabled: true
   state: started
   name: gdm

- name: enable gdm automatic login
  become: true
  ansible.builtin.copy:
    content: |
      # Start GDM configuraiton settings
      # Generated by ansible at {{ ansible_date_time.iso8601 }}

      [daemon]
      AutomaticLogin={{ ansible_user_id }}
      AutomaticLoginEnable=true

      [security]

      [xdmcp]

      [chooser]

      [debug]
      # Uncommend the line below to turn on debugging
      #Enable=true

      # End GDM configuration settings
    dest: /etc/gdm/custom.conf

- name: set theme
  when: gnome_theme is defined
  ansible.builtin.shell: |
    gsettings set org.gnome.desktop.interface gtk-theme "{{ gnome_theme }}"
    gsettings set org.gnome.desktop.wm.preferences theme "{{ gnome_theme }}"
    gsettings set org.gnome.desktop.interface icon-theme "{{ gnome_theme }}"
