---
- name: "install systemd-resolvconf"
  become: true
  community.general.pacman:
    name: systemd-resolvconf
    state: latest
    update_cache: true

- name: "create /etc/systemd/resolved.conf"
  when: nextdns_profile_id != "CHANGEME"
  become: true
  ansible.builtin.template:
    src: templates/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: '0644'

- name: "mask avahi-daemon service"
  become: true
  ansible.builtin.systemd:
    name: avahi-daemon.service
    enabled: false
    masked: true

- name: "mask avahi-daemon socket"
  become: true
  ansible.builtin.systemd:
   name: avahi-daemon.socket
   enabled: false
   masked: true

- name: "restart systemd-resolved"
  become: true
  ansible.builtin.systemd:
   name: systemd-resolved
   state: restarted
