---
- name: "restart networking"
  become: true
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted

- name: "locale setup"
  become: true
  shell: |
    locale-gen
    localectl set-locale LANG=en_US.UTF-8
