---
- name: create tmp dir
  ansible.builtin.tempfile:
    state: directory
  register: tmp_dir

- name: download sublime hq gpg key
  ansible.builtin.get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: "{{ tmp_dir.path }}/sublimehq-pub.gpg"

- name: add sublime hq gpg key to pacman keyring
  become: true
  ansible.builtin.shell: |
    pacman-key --add {{ tmp_dir.path }}/sublimehq-pub.gpg
    pacman-key --lsign-key 8A8F901A

- name: remove tmp dir
  ansible.builtin.file:
    path: "{{ tmp_dir.path }}"
    state: absent
  when: tmp_dir.path is defined

- name: add stable channel to pacman server list
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    line: '[sublime-text]'
    insertafter: EOF

- name: add stable channel to pacman server list
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    line: 'Server = https://download.sublimetext.com/arch/stable/x86_64'
    insertafter: EOF

- name: install sublime-text
  become: true
  community.general.pacman:
    name: sublime-text
    state: latest
    update_cache: true

- name: set sublime-text user prefs
  ansible.builtin.copy:
    src: user-prefs.json
    dest: "/home/{{ ansible_user_id }}/.config/sublime-text/Packages/User/Preferences.sublime-settings"
